global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 5s
    static_configs:
      - targets:
          - "localhost:9090"
  - job_name: "app"
    static_configs:
      - targets:
          - "goapp:8080"
